# Generated by Django 4.2.15 on 2024-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_tb_seller_phone_alter_tb_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
