# Generated by Django 4.2.15 on 2024-08-28 09:55

import app.product.models
from django.db import migrations, models
import django.db.models.deletion
import server.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product_category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='tb_product_subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, storage=server.storage.OverwriteStorage(), upload_to=app.product.models.subcategory_image_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.tb_product_category')),
            ],
        ),
    ]
