# Generated by Django 4.2.15 on 2024-08-28 11:25

import app.product.models
from django.db import migrations, models
import django.db.models.deletion
import server.storage
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_tb_seller_phone_alter_tb_seller_user'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, storage=server.storage.OverwriteStorage(), upload_to=app.product.models.product_image_path)),
                ('title', models.TextField()),
                ('price', models.IntegerField(max_length=7)),
                ('unit', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.tb_product_category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.tb_seller')),
            ],
        ),
    ]
