# Generated by Django 4.2.15 on 2024-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tb_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
