# Generated by Django 4.2.15 on 2024-08-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_tb_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_product',
            old_name='category',
            new_name='sub_category',
        ),
    ]
