# Generated by Django 4.2.15 on 2024-09-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_category_tb_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_product_subcategory',
            name='emoji',
            field=models.CharField(blank=True, default='🛒', max_length=250, null=True),
        ),
    ]
