# Generated by Django 4.2.15 on 2024-09-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_tb_product_subcategory_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_product',
            name='fixed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tb_product',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
