# Generated by Django 4.2.15 on 2024-09-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_tb_product_discount_tb_product_fixed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_product_subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.tb_product_category'),
        ),
    ]
