# Generated by Django 4.2.15 on 2024-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_tb_product_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_product',
            name='allowed_limit',
            field=models.IntegerField(default=1),
        ),
    ]
