# Generated by Django 4.2.15 on 2024-09-04 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_rename_category_tb_product_sub_category'),
        ('customer', '0004_alter_tb_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('delivered', 'Delivered')], default='processing', max_length=250)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('can_cancel', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.tb_address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.tb_customer')),
            ],
        ),
        migrations.CreateModel(
            name='tb_order_item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.tb_order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tb_product')),
            ],
        ),
    ]
