# Generated by Django 4.2.15 on 2024-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_tb_order_item_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_order_item',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tb_order_item',
            name='buy_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
