# Generated by Django 4.2.15 on 2024-09-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_tb_product_subcategory_category'),
        ('order', '0005_alter_tb_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.tb_product'),
        ),
    ]
