# Generated by Django 4.2.15 on 2024-09-03 18:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('alt_phone', models.CharField(max_length=10)),
                ('city_or_town', models.CharField(max_length=250)),
                ('pin', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('landmark', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.tb_customer')),
            ],
        ),
    ]
