# Generated by Django 4.2.15 on 2024-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_tb_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_address',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
