# Generated by Django 4.2.15 on 2024-09-02 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0007_rename_category_tb_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_wishlist_item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tb_product')),
            ],
        ),
        migrations.CreateModel(
            name='tb_wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('district', models.CharField(blank=True, max_length=250, null=True)),
                ('is_for_everyone', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, related_name='wishlist', to='wishlist.tb_wishlist_item')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customer.tb_customer')),
            ],
        ),
    ]
