# Generated by Django 4.2.15 on 2024-09-05 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_block_district',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='tb_block_pincode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=250)),
            ],
        ),
    ]
