# Generated by Django 4.2.15 on 2024-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_block_district',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_block_pincode',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
